# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy CPU
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy CPU app
    runs-on: ubuntu-latest
    concurrency: deploy-group-cpu
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Set Fly secrets
      - name: Set Fly secrets
        run: |
          flyctl secrets set --stage --app "content-moderation-server-cpu" GCP_CREDENTIALS="$GCP_CREDENTIALS"
          flyctl secrets set --stage --app "content-moderation-server-cpu" GCS_BUCKET="$GCS_BUCKET"
          flyctl secrets set --stage --app "content-moderation-server-cpu" GCS_EMBEDDINGS_PATH="$GCS_EMBEDDINGS_PATH"
          flyctl secrets set --stage --app "content-moderation-server-cpu" GCS_PROMPT_PATH="$GCS_PROMPT_PATH"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
          GCS_EMBEDDINGS_PATH: ${{ secrets.GCS_EMBEDDINGS_PATH }}
          GCS_PROMPT_PATH: ${{ secrets.GCS_PROMPT_PATH }}

      - name: check fly secrets
        run: |
          flyctl secrets list --app content-moderation-server-cpu
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Check fly status
      - name: Check fly status
        run: |
          flyctl status --app content-moderation-server-cpu
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      # Deploy to Fly
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only --config src_deploy/cpu.fly.toml --dockerfile ./src_deploy/cpu.Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
